### ISSUE TITLE
Onboarding user experience

### ISSUE THREAD

**Issue by super3** [Storj/metadisk-api#10]
Tome, when you have some time, will you think about the initial successful sign up landing and how to step the user through bucket creation, pairing their application, and installing client tools/API docs depending on the developer's platform?

I can join a call with you next week to share some ideas.

**Comment by gordonwritescode** [comment]
Implemented at the API level here: https://github.com/Storj/metadisk-api/commit/33746a983ab081b83ed9196740fd880eefe72961

**Comment by gordonwritescode** [comment]
Oh weird, @tome, I wrote the above, not @super3
