### ISSUE TITLE
MongoDB integration review and deployment plan

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/metadisk-api#16]
Before MetaDisk is production ready, we need to review some of the following:

* Indexing and schema design
* Replication vs sharding for our use case
* *TODO*

**Comment by gordonwritescode** [comment]
@super3 @frdwrd

**Comment by super3** [comment]
@gordonwritescode I'd go with simple and highly redundant replication for now. Erasure encoding is something we can just slip in there layer.

**Comment by niahmiah** [comment]
Paraphrasing from slack discussion (btw, do you guys have a Storj slack?)

On a few of the collections, there seems to be a 2nd key that you are really using as your primary key (unique index)

You can use any type you want for _id. We could move "key" to _id for pubkey, and "token" to _id for tokens. We can move "email" to _id for users.

Then there would be a true primary key and only the 1 unique index per collection. This is better for performance (fewer indices to update), and is **required** for sharding, if that need arises.

**Comment by super3** [comment]
Yeah, slack is here:
http://storj.slack.io

On Thu, Feb 25, 2016 at 1:49 PM, niahmiah <notifications@github.com> wrote:

> Paraphrasing from slack discussion (btw, do you guys have a Storj slack?)
>
> On a few of the collections, there seems to be a 2nd key that you are
> really using as your primary key (unique index)
>
> You can use any type you want for _id. We could move "key" to _id for
> pubkey, and "token" to _id for tokens. We can move "email" to _id for users.
>
> Then there would be a true primary key and only the 1 unique index per
> collection. This is better for performance (fewer indices to update), and
> is *required* for sharding, if that need arises.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Storj/metadisk-api/issues/16#issuecomment-188925745>.
>



-- 
Shawn Wilkinson
Lead Developer and Founder | storj.io
me@super3.org | super3.org

**Comment by gordonwritescode** [comment]
TODO:

* [ ] Update API routes that use `File` to resolve shard hashes from `Hash` model

**Comment by gordonwritescode** [comment]
@niahmiah thanks for working with us today :beers:
