### ISSUE TITLE
clear type password HTTP basic authentication

### ISSUE THREAD

**Issue by littleskunk** [Storj/metadisk-api#25]
https://github.com/Storj/metadisk-api/blob/master/doc/auth.md#http-basic

This should work but i get invalid password response:
`curl -u user:SHA256 -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'https://api.metadisk.org/keys'`

If i use my clear type password it is working (I am getting an other error message because authentication was successfull but the api call not):
`curl -u user:password -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'https://api.metadisk.org/keys'`

**Comment by gordonwritescode** [comment]
MetaDisk API expects the SHA256 of the password when you register - then it runs another round of SHA256 before storing. So it sounds like you did not SHA256 your password on the client before registering your account.

I will add validation to ensure that the submitted password is the proper number of bits on register.
