### ISSUE TITLE
Add usefull information to API documentation

### ISSUE THREAD

**Issue by littleskunk** [Storj/metadisk-api#26]
Users section:
Easy to understand and it is possible to send the request direct. Very good.

Keys section:
Basic authentication missing. Please add them to the curl examples of all the api calls.

Buckets section:
Basic authentication missing. Please add them to the curl examples of all the api calls.
Post buckets has some more parameters. A short discription would be nice. What is storage and transfer? What values are allowed?
Post tokens. A list of available operations please. How do I create a token for 2 or more operations?
Put files. curl missing file and filesize. How about Content-Type?

**Comment by littleskunk** [comment]
Returning API URL would be nice as well. Like github API: 
https://api.github.com/repos/Storj/driveshare-gui/releases

Example:
Create or Get bucket should return file upload url. Easy to use for the next step.

**Comment by gordonwritescode** [comment]
Let's move this to https://github.com/Storj/metadisk-gui - since that is where the documentation will live. Metadisk API only provides the OpenAPI Specification as JSON.
