### ISSUE TITLE
buckets/{id}/files/{hash} changed but documentation not updated

### ISSUE THREAD

**Issue by littleskunk** [Storj/metadisk-api#27]
buckets/{id}/files/{hash} returns
```
[
  {
    "hash": "<hash>",
    "token": "<token>",
    "operation": "PULL",
    "channel": "ws://162.243.48.250:4000"
  }
]
```

Documentation is not updated:
http://storj.github.io/metadisk-api/#!/buckets/get_buckets_id_files_hash

I didn't check the other API calls.

**Comment by gordonwritescode** [comment]
Ah yes, will update the schema, thanks. This is the only change to the API.

**Comment by gordonwritescode** [comment]
Fixed - next release.
