### ISSUE TITLE
error = "Shard data not found"

### ISSUE THREAD

**Issue by donAFRO** [Storj/metadisk-api#28]
When I am trying to save data (with PUT) on https://api.metadisk.org with Metadisk API I got error from Success callback that says **error = "Shard data not found"** and the file is not being stored....
I am using Swift with Alamofire and creating a Bucket worked fine...

**Comment by littleskunk** [comment]
Some more bad results:
`curl -u user:password -X PUT --header "Content-Type: multipart/form-data" --header "Accept: application/json" -F file="@C:\Storj.jpg" --header "x-Filesize: 94209" --header "x-token: {token}" "https://api.metadisk.org/buckets/{id}/files"`

Most of the time i get this response:
`curl: (52) Empty reply from server`
Only once i had this response:
`{"error":"Calculated hash does not match the expected result"}`

And now upload the same file with a wrong file size.
`curl -u user:password -X PUT --header "Content-Type: multipart/form-data" --header "Accept: application/json" -F file="@C:\Storj.jpg" --header "x-Filesize: 1" --header "x-token: {token}" "https://api.metadisk.org/buckets/{id}/files"`

Metadisk-API 0.1.3. was responding with a file size error. Now i get only `curl: (52) Empty reply from server`

**Comment by donAFRO** [comment]
I tried that again and got three times Request timeout and then this error 
**error = "ENOENT: no such file or directory, scandir '/root/.storjnode/shards/e4d559d58a38452562fe7ababa3f558ee43823f8/challenges'";**

**Comment by gordonwritescode** [comment]
I suspect this is a bug with MetaDisk selecting the farmer that holds the shard. Will resolve ASAP and release a patch early next week.

**Comment by gordonwritescode** [comment]
Correction - *farmer that holds the shard contract*

**Comment by dlmac** [comment]
{"error":"ENOENT: no such file or directory, scandir '/root/.storjnode/shards/65a60e97ad3d70cae84a50c2178d0899774ca962/challenges'"}

**Comment by gordonwritescode** [comment]
Okay, so this *must* be an issue with metadisk selecting the wrong farmer for retrieval, because @dlmac's shard *is* known by one of our test farmers:

```
root@storjmvp-farmer-03:~/.storjnode/shards/65a60e97ad3d70cae84a50c2178d0899774ca962# ls
challenges  contracts  meta  shard.data  trees
```

However, the shard data is empty and the contract is incomplete:

```
root@storjmvp-farmer-03:~/.storjnode/shards/65a60e97ad3d70cae84a50c2178d0899774ca962# cat shard.data 
root@storjmvp-farmer-03:~/.storjnode/shards/65a60e97ad3d70cae84a50c2178d0899774ca962# cat contracts/593844dc7f0076a1aeda9a6b9788af17e67c1052 
{"audit_count":12,"data_hash":"65a60e97ad3d70cae84a50c2178d0899774ca962","data_size":497467,"farmer_id":"f3c404e50d3954af6a97e899912ccf75df0e6199","farmer_signature":"H5KUlKDZaz1FbXoYM4ntdkACjaJIH2USIod0yQkuiXmxJuLJgsT1bLgWil/99TSSBU8EB9t4nc/572mgu4Uf2Nk=","payment_destination":"1PDv2GCSYyPHXo9PkvLdY5cps4zsuP7k9R","payment_download_price":0,"payment_storage_price":0,"renter_id":"593844dc7f0076a1aeda9a6b9788af17e67c1052","renter_signature":null,"store_begin":1457833200410,"store_end":1457833800410,"type":"56ce3e837f575827cb5a94e2b609756a48fa4a3882f5e762b262af31f432878d"}
```

This leads me to believe that there is an issue with how metadisk is choosing the farmer in between operations. I will deploy what I believe to be a fix - though, since I'm not able to reproduce the issue myself, I will leave this open until the fix is confirmed.

**Comment by dlmac** [comment]
{"error":"Failed to load the shard audit trees"}

**Comment by gordonwritescode** [comment]
Okay I think I've nailed this down to a bug in node-storj#FSStorageAdapter
