### ISSUE TITLE
improve error messages

### ISSUE THREAD

**Issue by littleskunk** [Storj/metadisk-api#29]
Key already exists:
`curl -u user:password -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "key": "{key}" }' 'https://api.metadisk.org/keys'`
`{"error":"E11000 duplicate key error collection: metadisk-api.publickeys index: _id_ dup key: { : \"{key}\" }"}`

**Comment by gordonwritescode** [comment]
Fixed - next release.
