### ISSUE TITLE
token can be used more than once

### ISSUE THREAD

**Issue by littleskunk** [Storj/metadisk-api#32]
PULL token ( get buckets/{id}/files/{hash} ) and PUSH token ( put /buckets/{id}/files ) can be used more than once.

One open question: Should the token expire in any case (for example failed upload because of wrong filesize)?

**Comment by gordonwritescode** [comment]
I think that the token should expire upon successful use at the authorization layer (to keep with logic decoupled from individual endpoints). This would mean a failed request would indeed require a new token to be created to try again.

**Comment by gordonwritescode** [comment]
Fixed - next release.
