### ISSUE TITLE
Error when uploading duplicate files.

### ISSUE THREAD

**Issue by brandonparee** [Storj/metadisk-api#33]
When uploading a duplicate file, even in a separate bucket I get this error. 

`Error [Error: E11000 duplicate key error collection: metadisk-api.files index: _id_ dup key: { : "1d1f5504410f40f6628039ca8422ef1d53072248" }]`

**Comment by brandonparee** [comment]
Since this is probably a related issue (dealing with duplicate files):

When you upload a file that is a duplicate, but has a different name, the file is renamed in a bucket rather than having two copies of the file. 

For example. I have two files that have the same contents, file.js and file-duplicate.js. If I have already uploaded file.js and am trying to upload file-duplicate.js, only file-duplicate.js remains after upload.

**Comment by gordonwritescode** [comment]
Resolved as of v0.2.2
