### ISSUE TITLE
ECDSA Signature security problems

### ISSUE THREAD

**Issue by littleskunk** [Storj/metadisk-api#37]
1) Same key can be registered twice.
`{ "key": "04:38:74:de:22:53:6d:ec:c5:50:82:57:cc:80:6a:9e:5a:f5:e8:be:6a:80:05:68:43:d5:c0:c2:b1:12:90:34:30:f9:a4:6c:12:8c:a1:7e:30:e2:fb:54:f5:41:41:61:85:dd:a2:df:87:8a:db:b9:0d:66:81:14:52:f4:16:21:25" }`
`{ "key": "043874de22536decc5508257cc806a9e5af5e8be6a80056843d5c0c2b112903430f9a46c128ca17e30e2fb54f541416185dda2df878adbb90d66811452f4162125" }`
2) First key has to be register by using HTTP basic auth. Optional public key for the registration would be better.
3) Same signature can be used more than once. `In addition to the parameters required for each individual request, you must also include a __nonce parameter. This value should be an integer and must be incremented with every request.` I did not increment the value.

**Comment by gordonwritescode** [comment]
First issue can be fixed by sanitizing input before validating the key. 

Second one is a bug: https://github.com/Storj/metadisk-api/blob/master/lib/server/middleware/authenticate.js#L96 (checking less than but not equal to)

Great finds @skunk!

**Comment by hwkns** [comment]
I agree with @littleskunk that adding an optional public key param in the registration request would be nice.  Other issues:

a) There is no nonce required for GET or DELETE requests, leaving them vulnerable to replay attacks (leaking sensitive data in the case of GET, or deleting critical data in the case of DELETE).

b) A nonce should be a unique, random value (preferably a UUID), and should be used in conjunction with a timestamp, as described here: http://stackoverflow.com/a/6876907/1784296  Also, perhaps the nonce should live in the header?

**Comment by gordonwritescode** [comment]
Solved:

* [x] Same key can be registered twice by disallowing non-hexidecimal characters like `:`
* [x] Signature re-use bug fixed
* [x] No nonce checking on GET and DELETE

---

* For the pubkey registration on user signup, let's open a separate issue and track it there
* For the suggested changes for the nonce format, let's do the same and discuss

**Comment by littleskunk** [comment]
`curl -u user:password -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "key": "29:74:8d:7f:66:bc:40:e1:bd:2d:e4:f4:b5:77:ef:8d" }' 'https://api.metadisk.org/keys'`

Expected error message:
`{"error":"Invalid public key supplied: Must not contain non-hexidecimal characters like ":"}`

But I get this error message:
`{"error":"Invalid public key supplied: Must not contain non-hexidecimal characters like \":\""}`

**Comment by gordonwritescode** [comment]
That is expected. The first example is not valid JSON (double quotes must be escaped).
