### ISSUE TITLE
"error":"Invalid email or password"

### ISSUE THREAD

**Issue by christophe-marteau** [Storj/metadisk-api#38]
Since yesterday I'm'not able to authenticate to the API anymore 

/usr/bin/curl -v -S --basic --user mail@example.net:password -X GET --header 'Accept: application/json' https://api.metadisk.org/buckets

give me 

*   Trying 162.243.72.56...
* Connected to api.metadisk.org (162.243.72.56) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: api.metadisk.org (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=api.metadisk.org
* 	 start date: Thu, 03 Mar 2016 17:02:00 GMT
* 	 expire date: Wed, 01 Jun 2016 17:02:00 GMT
* 	 issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X1
* 	 compression: NULL
* ALPN, server did not agree to a protocol
* Server auth using Basic with user 'mail@example.net'
> GET /buckets HTTP/1.1
> Host: api.metadisk.org
> Authorization: Basic cmlja2Vubnktc3RvcmphcGlAdm90ZXotY3RodWxodS5uZXQ6cGxpY3Bsb2M=
> User-Agent: curl/7.43.0
> Accept: application/json
> 
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< Vary: Origin
< Access-Control-Allow-Credentials: true
< Content-Type: application/json; charset=utf-8
< Content-Length: 37
< ETag: W/"25-06BquQnCwmlHB2RmaLK0OQ"
< Date: Wed, 16 Mar 2016 08:08:02 GMT
< Connection: keep-alive
< 
* Connection #0 to host api.metadisk.org left intact
{"error":"Invalid email or password"}

It was working before yesterday. Is there any changes ?

Thx

**Comment by littleskunk** [comment]
gordon [16:28] 
@channel: i've made some changes to the files/buckets/references schemas as well as the corresponding indexes for some of them. i'll be dropping the database around 1pm EST today - all data will be lost. i realize this may be an inconvenience for some of you, but in the interest of moving forward quickly, at this stage it doesn't make sense to perform any sort of migration.

**Comment by christophe-marteau** [comment]
No problem for me, but where can I be informed that the API is not available for the moment. It's just to avoid of submitting bugs and waste your time ...

Thx

**Comment by littleskunk** [comment]
http://slack.storj.io/
Channel metadisk

**Comment by christophe-marteau** [comment]
Thx
