### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by robertsdotpm** [Storj/metadisk-api#43]
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>

Environment Python 3.4 on Windows.

Will update if I find a work around.

**Comment by gordonwritescode** [comment]
I am almost certain this needs to be handled on the python client side by ensuring that the proper CA chain is being used by the request library.

Please correct me if I am wrong.

**Comment by gordonwritescode** [comment]
mentioning @phutchins for visibility in case the issue is with letsencrypt

**Comment by phutchins** [comment]
@robertsdotpm, could you include the error that you're getting?

**Comment by robertsdotpm** [comment]
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

I found the fix for it. It was client side.

**Comment by gordonwritescode** [comment]
:+1:
